/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Dao.DaoEntrega;
import Dao.DaoPedido;
import Dao.DaoVehiculo;
import Modelo.Entrega;
import Modelo.Pedido;
import Modelo.Vehiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class Entregas extends javax.swing.JInternalFrame {
DaoEntrega dao = new DaoEntrega();
Entrega e = new Entrega();
DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Entregas
     */
    public Entregas() {
        initComponents();
        listar();
    }
    
public void listar() {

    ArrayList<Entrega> lista = dao.listar();

    modelo = (DefaultTableModel) tblEntregas.getModel();
    modelo.setRowCount(0);

    Object[] fila = new Object[7];

    for (int i = 0; i < lista.size(); i++) {

        fila[0] = lista.get(i).getCodigo();
        fila[1] = lista.get(i).getFecha();
        fila[2] = lista.get(i).getTiempo();
        fila[3] = lista.get(i).getCo2();
        fila[4] = lista.get(i).getCodigoVehiculo();
        fila[5] = lista.get(i).getCodigoPedido();
        fila[6] = lista.get(i).getEstado();

        modelo.addRow(fila);
    }

    tblEntregas.setModel(modelo);
}

public void limpiar() {
    txtCodigo.setText("");
    txtFecha.setText("");
    txtTiempo.setText("");
    txtCo2.setText("");
    txtCodigoVehiculo.setText("");
    txtCodigoPedido.setText("");
    txtEstado.setText("");
    txtCodigo.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        txtCodigoVehiculo = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtCo2 = new javax.swing.JTextField();
        txtCodigoPedido = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntregas = new javax.swing.JTable();
        btnProcesarEntrega = new javax.swing.JButton();
        btnCalcularEntrega = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Tiempo:");

        jLabel3.setText("Codigo Vehiculo:");

        jLabel4.setText("Estado:");

        jLabel5.setText("Fecha:");

        jLabel6.setText("CO2 evitado (kg):");

        jLabel7.setText("Codigo pedido:");

        txtTiempo.addActionListener(this::txtTiempoActionPerformed);

        txtCodigoPedido.addActionListener(this::txtCodigoPedidoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        tblEntregas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Fecha", "Tiempo", "CO2 evitado", "Codigo Vehiculo", "Codigo pedido", "Estado"
            }
        ));
        tblEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntregasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEntregas);

        btnProcesarEntrega.setText("Procesar entrega");
        btnProcesarEntrega.addActionListener(this::btnProcesarEntregaActionPerformed);

        btnCalcularEntrega.setText("Calcular entrega");
        btnCalcularEntrega.addActionListener(this::btnCalcularEntregaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstado)
                                    .addComponent(txtCodigoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcesarEntrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcularEntrega)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtCodigoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnProcesarEntrega)
                    .addComponent(btnCalcularEntrega))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void txtCodigoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPedidoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
    e.setCodigo(Integer.parseInt(txtCodigo.getText().trim()));
    e.setFecha(txtFecha.getText().trim());
    e.setTiempo(Double.parseDouble(txtTiempo.getText().trim()));
    e.setCo2(Double.parseDouble(txtCo2.getText().trim()));
    e.setCodigoVehiculo(Integer.parseInt(txtCodigoVehiculo.getText().trim()));
    e.setCodigoPedido(Integer.parseInt(txtCodigoPedido.getText().trim()));
    e.setEstado(txtEstado.getText().trim());

    boolean ok = dao.insertar(e);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Entrega guardada correctamente");
        listar();
        limpiar();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo guardar la entrega");
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
    e.setCodigo(Integer.parseInt(txtCodigo.getText().trim()));
    e.setFecha(txtFecha.getText().trim());
    e.setTiempo(Double.parseDouble(txtTiempo.getText().trim()));
    e.setCo2(Double.parseDouble(txtCo2.getText().trim()));
    e.setCodigoVehiculo(Integer.parseInt(txtCodigoVehiculo.getText().trim()));
    e.setCodigoPedido(Integer.parseInt(txtCodigoPedido.getText().trim()));
    e.setEstado(txtEstado.getText().trim());

    boolean ok = dao.modificar(e);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Entrega modificada correctamente");
        listar();
        limpiar();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo modificar la entrega");
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error al modificar: " + ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
    int fila = tblEntregas.getSelectedRow();

    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "Seleccione una entrega de la tabla");
        return;
    }

    int codigo = Integer.parseInt(tblEntregas.getValueAt(fila, 0).toString());

    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea eliminar esta entrega?",
            "Eliminar entrega",
            JOptionPane.YES_NO_OPTION
    );

    if (opcion == JOptionPane.YES_OPTION) {

        boolean ok = dao.eliminar(codigo);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Entrega eliminada correctamente");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar la entrega");
        }
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntregasMouseClicked
        int fila = tblEntregas.getSelectedRow();

if (fila >= 0) {
    txtCodigo.setText(tblEntregas.getValueAt(fila, 0).toString());
    txtFecha.setText(tblEntregas.getValueAt(fila, 1).toString());
    txtTiempo.setText(tblEntregas.getValueAt(fila, 2).toString());
    txtCo2.setText(tblEntregas.getValueAt(fila, 3).toString());
    txtCodigoVehiculo.setText(tblEntregas.getValueAt(fila, 4).toString());
    txtCodigoPedido.setText(tblEntregas.getValueAt(fila, 5).toString());
    txtEstado.setText(tblEntregas.getValueAt(fila, 6).toString());
}        // TODO add your handling code here:
    }//GEN-LAST:event_tblEntregasMouseClicked

    private void btnProcesarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarEntregaActionPerformed
        try {
    Entrega en = new Entrega();

    en.setCodigo(Integer.parseInt(txtCodigo.getText().trim()));
    en.setFecha(txtFecha.getText().trim());
    en.setTiempo(Double.parseDouble(txtTiempo.getText().trim()));
    en.setCo2(Double.parseDouble(txtCo2.getText().trim()));
    en.setCodigoVehiculo(Integer.parseInt(txtCodigoVehiculo.getText().trim()));
    en.setCodigoPedido(Integer.parseInt(txtCodigoPedido.getText().trim()));
    en.setEstado("EN ENTREGA");

    DaoEntrega daoTransaccion = new DaoEntrega();

    boolean procesado = daoTransaccion.procesarEntrega(en);

    if (procesado) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Entrega procesada correctamente.\n"
                + "Pedido actualizado a EN ENTREGA.\n"
                + "Vehículo actualizado a OCUPADO."
        );

        listar();
        limpiar();

    } else {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se pudo procesar la entrega.\n"
                + "Verifique que el vehículo esté DISPONIBLE."
        );
    }

} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al procesar entrega: " + ex.getMessage()
    );
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcesarEntregaActionPerformed

    private void btnCalcularEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEntregaActionPerformed
                                // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularEntregaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularEntrega;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnProcesarEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEntregas;
    private javax.swing.JTextField txtCo2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoPedido;
    private javax.swing.JTextField txtCodigoVehiculo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
