/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Dao.DaoPedido;
import Modelo.Pedido;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class Pedidos extends javax.swing.JInternalFrame {
DaoPedido dao = new DaoPedido();
Pedido p = new Pedido();
DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
        listar();
    }
public void listar() {

    ArrayList<Pedido> lista = dao.listar();

    modelo = (DefaultTableModel) tblPedidos.getModel();
    modelo.setRowCount(0);

    Object[] fila = new Object[5];

    for (int i = 0; i < lista.size(); i++) {

        fila[0] = lista.get(i).getCodigo();
        fila[1] = lista.get(i).getDescripcion();
        fila[2] = lista.get(i).getDistancia();
        fila[3] = lista.get(i).getCodigoCliente();
        fila[4] = lista.get(i).getEstado();

        modelo.addRow(fila);
    }

    tblPedidos.setModel(modelo);
}

public void limpiar() {
    txtCodigo.setText("");
    txtDescripcion.setText("");
    txtDistancia.setText("");
    txtCodigoCliente.setText("");
    txtEstado.setText("");
    txtCodigo.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDistancia = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Distancia:");

        jLabel3.setText("Estado:");

        jLabel4.setText("Descripcion:");

        jLabel5.setText("Codigo Cliente:");

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        txtCodigoCliente.addActionListener(this::txtCodigoClienteActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Distancia", "Código Cliente", "Estado"
            }
        ));
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(txtDistancia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
    p.setCodigo(Integer.parseInt(txtCodigo.getText().trim()));
    p.setDescripcion(txtDescripcion.getText().trim());
    p.setDistancia(Double.parseDouble(txtDistancia.getText().trim()));
    p.setCodigoCliente(Integer.parseInt(txtCodigoCliente.getText().trim()));
    p.setEstado(txtEstado.getText().trim());

    boolean ok = dao.modificar(p);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Pedido modificado correctamente");
        listar();
        limpiar();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo modificar el pedido");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
    p.setCodigo(Integer.parseInt(txtCodigo.getText().trim()));
    p.setDescripcion(txtDescripcion.getText().trim());
    p.setDistancia(Double.parseDouble(txtDistancia.getText().trim()));
    p.setCodigoCliente(Integer.parseInt(txtCodigoCliente.getText().trim()));
    p.setEstado(txtEstado.getText().trim());

    boolean ok = dao.insertar(p);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Pedido guardado correctamente");
        listar();
        limpiar();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo guardar el pedido");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
    int fila = tblPedidos.getSelectedRow();

    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "Seleccione un pedido de la tabla");
        return;
    }

    int codigo = Integer.parseInt(tblPedidos.getValueAt(fila, 0).toString());

    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea eliminar este pedido?",
            "Eliminar pedido",
            JOptionPane.YES_NO_OPTION
    );

    if (opcion == JOptionPane.YES_OPTION) {

        boolean ok = dao.eliminar(codigo);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Pedido eliminado correctamente");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el pedido");
        }
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        int fila = tblPedidos.getSelectedRow();

if (fila >= 0) {
    txtCodigo.setText(tblPedidos.getValueAt(fila, 0).toString());
    txtDescripcion.setText(tblPedidos.getValueAt(fila, 1).toString());
    txtDistancia.setText(tblPedidos.getValueAt(fila, 2).toString());
    txtCodigoCliente.setText(tblPedidos.getValueAt(fila, 3).toString());
    txtEstado.setText(tblPedidos.getValueAt(fila, 4).toString());
}        // TODO add your handling code here:
    }//GEN-LAST:event_tblPedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables
}
